[server]
port = 8080
enableStaticServing = true

[client]
showErrorDetails = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "rgb(29, 154, 214, 0.9)"
backgroundColor = "rgb(29, 154, 214, 0.5)"
secondaryBackgroundColor="rgb(52, 52, 52, 0.9)"
textColor="#EBEBEB"
font="sans serif"
